### PR TITLE
Fixes 404 error on README.MD

### PR DESCRIPTION
**Pull request by nathaliabruno**

### CODE REVIEW

**Comment by kbaldauf** [comment]
Thanks @nathaliabruno! Tagging @kevgo and @matthandlersux for visibility.

**Comment by matthandlersux** [comment]
👍 also @ChrisMM how did we miss this :'(

**Comment by matthandlersux** [comment]
@nathaliabruno thanks!

**Comment by kevgo** [comment]
A ❤️ from me as well. Thanks for fixing this!

**Comment by nathaliabruno** [comment]
For nothing. I did it because I know that is very hard provide good documentations. And you do it very well. 😉👍

**Pull request merged**
